### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by roy-work** [sachaos/viddy#15]
It had been running for quite some time without issue (it had been watching that command for several hours), so not entirely sure what happened here:

```
» viddy k get po -A

panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0001a6000)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:243 +0x87
panic(0x11abf00, 0xc0004b4bd0)
	/opt/hostedtoolcache/go/1.16.7/x64/src/runtime/panic.go:965 +0x1b9
github.com/rivo/tview.(*TextView).Draw(0xc00011e300, 0x11f9cd0, 0xc00011c480)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/textview.go:1017 +0xf65
github.com/rivo/tview.(*Flex).Draw(0xc00007b1a0, 0x11f9cd0, 0xc00011c480)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/flex.go:179 +0x292
github.com/rivo/tview.(*Flex).Draw(0xc00007b170, 0x11f9cd0, 0xc00011c480)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/flex.go:179 +0x292
github.com/rivo/tview.(*Application).draw(0xc0001a6000, 0x0)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:603 +0xd9
github.com/rivo/tview.(*Application).Draw.func1()
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:556 +0x2a
github.com/rivo/tview.(*Application).Run(0xc0001a6000, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624165335-29d673af0ce2/application.go:380 +0xa2d
main.(*Viddy).Run(0xc00012edc0, 0x7ffeefbff44e, 0x1)
	/home/runner/work/viddy/viddy/viddy.go:514 +0x10ae
main.main()
	/home/runner/work/viddy/viddy/main.go:43 +0x1ec
```

Edit: been using `viddy` a lot more today. (I'm essentially a new user of it.) Running into this fairly reliably; seems like just leaving it running for a long length of time suffices.

**Comment by sachaos** [comment]
Thank you for your reporting.

This issue might be related to this bug.
https://github.com/rivo/tview/issues/636
